services:
  codesphera:
    image: ghcr.io/iamgreggarcia/codesherpa:latest
    build:
      context: .
    ports:
      - "3000"
    volumes:
      - ./static:/app/static
    command: python3 -c "import localserver.main; localserver.main.start()"
